set -eo pipefail

cat <<EOF | yq  ".data.env = \"$(env)\""
apiVersion: v1
kind: ConfigMap
metadata:
  name: blablablablablablabla
data:
  ARGOCD_APP_NAME: $ARGOCD_APP_NAME
  ARGOCD_APP_NAMESPACE: $ARGOCD_APP_NAMESPACE
  ARGOCD_APP_REVISION: $ARGOCD_APP_REVISION
  ARGOCD_APP_REVISION_SHORT: $ARGOCD_APP_REVISION_SHORT
  ARGOCD_APP_SOURCE_REPO_TOP_LEVEL: $ARGOCD_APP_SOURCE_REPO_TOP_LEVEL
  ARGOCD_APP_SOURCE_PATH: $ARGOCD_APP_SOURCE_PATH
  ARGOCD_APP_SOURCE_REPO_URL: $ARGOCD_APP_SOURCE_REPO_URL
  ARGOCD_APP_SOURCE_TARGET_REVISION: $ARGOCD_APP_SOURCE_TARGET_REVISION
  KUBE_VERSION: "$KUBE_VERSION"
  KUBE_API_VERSIONS: $KUBE_API_VERSIONS
EOF
